from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib.colors import HexColor
import io
import re

class PDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()
    
    def _create_custom_styles(self):
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=HexColor('#1A73E8')
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            spaceBefore=20,
            textColor=HexColor('#333333')
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=8,
            alignment=TA_JUSTIFY,
            leading=16
        ))
        
        self.styles.add(ParagraphStyle(
            name='KeyPoint',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=6,
            leftIndent=20,
            bulletIndent=10
        ))
    
    def generate_summary_pdf(self, title: str, summary_data: dict) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, 
                               rightMargin=50, leftMargin=50,
                               topMargin=50, bottomMargin=50)
        
        story = []
        
        story.append(Paragraph("AI Video Summarizer", self.styles['CustomTitle']))
        story.append(Spacer(1, 10))
        
        clean_title = self._clean_text(title)
        story.append(Paragraph(f"Video: {clean_title}", self.styles['CustomHeading']))
        story.append(Spacer(1, 20))
        
        full_summary = summary_data.get('full_summary', '')
        if full_summary:
            paragraphs = full_summary.split('\n')
            for para in paragraphs:
                para = para.strip()
                if para:
                    if para.startswith('##'):
                        clean_heading = self._clean_text(para.replace('#', '').strip())
                        story.append(Paragraph(clean_heading, self.styles['CustomHeading']))
                    elif para.startswith('###'):
                        clean_subheading = self._clean_text(para.replace('#', '').strip())
                        story.append(Paragraph(clean_subheading, self.styles['Heading3']))
                    elif para.startswith('**') and para.endswith('**'):
                        clean_bold = self._clean_text(para.replace('**', ''))
                        story.append(Paragraph(f"<b>{clean_bold}</b>", self.styles['CustomBody']))
                    elif para.startswith('-') or para.startswith('*'):
                        clean_item = self._clean_text(para.lstrip('-*').strip())
                        story.append(Paragraph(f"• {clean_item}", self.styles['KeyPoint']))
                    else:
                        clean_para = self._clean_text(para)
                        story.append(Paragraph(clean_para, self.styles['CustomBody']))
                    story.append(Spacer(1, 4))
        
        key_points = summary_data.get('key_points', [])
        if key_points:
            story.append(Spacer(1, 20))
            story.append(Paragraph("Key Takeaways", self.styles['CustomHeading']))
            for point in key_points:
                clean_point = self._clean_text(point)
                story.append(Paragraph(f"• {clean_point}", self.styles['KeyPoint']))
        
        story.append(Spacer(1, 30))
        story.append(Paragraph("Generated by AI Video Summarizer", 
                              ParagraphStyle(name='Footer', fontSize=9, 
                                           alignment=TA_CENTER, 
                                           textColor=HexColor('#888888'))))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
    
    def generate_quiz_pdf(self, title: str, questions: list) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                               rightMargin=50, leftMargin=50,
                               topMargin=50, bottomMargin=50)
        
        story = []
        
        story.append(Paragraph("AI Video Quiz", self.styles['CustomTitle']))
        story.append(Spacer(1, 10))
        
        clean_title = self._clean_text(title)
        story.append(Paragraph(f"Video: {clean_title}", self.styles['CustomHeading']))
        story.append(Paragraph(f"Total Questions: {len(questions)}", self.styles['CustomBody']))
        story.append(Spacer(1, 20))
        
        for i, q in enumerate(questions, 1):
            clean_question = self._clean_text(q.get('question', ''))
            story.append(Paragraph(f"<b>Question {i}:</b> {clean_question}", self.styles['CustomBody']))
            story.append(Spacer(1, 8))
            
            options = q.get('options', [])
            for j, opt in enumerate(options):
                clean_opt = self._clean_text(opt)
                letter = chr(65 + j)
                story.append(Paragraph(f"    {letter}) {clean_opt}", self.styles['KeyPoint']))
            
            story.append(Spacer(1, 20))
        
        story.append(Spacer(1, 30))
        story.append(Paragraph("--- ANSWER KEY ---", self.styles['CustomHeading']))
        story.append(Spacer(1, 10))
        
        for i, q in enumerate(questions, 1):
            correct = self._clean_text(q.get('correct_answer', ''))
            explanation = self._clean_text(q.get('explanation', ''))
            story.append(Paragraph(f"<b>Q{i}:</b> {correct}", self.styles['CustomBody']))
            if explanation:
                story.append(Paragraph(f"<i>Explanation: {explanation}</i>", self.styles['KeyPoint']))
            story.append(Spacer(1, 8))
        
        story.append(Spacer(1, 30))
        story.append(Paragraph("Generated by AI Video Summarizer",
                              ParagraphStyle(name='Footer', fontSize=9,
                                           alignment=TA_CENTER,
                                           textColor=HexColor('#888888'))))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
    
    def _clean_text(self, text: str) -> str:
        if not text:
            return ""
        text = re.sub(r'[<>&]', lambda m: {'<': '&lt;', '>': '&gt;', '&': '&amp;'}[m.group()], text)
        text = text.replace('**', '')
        text = text.replace('###', '')
        text = text.replace('##', '')
        text = text.replace('#', '')
        return text.strip()
